using dotnetNES.Engine.Models;
using System.Collections.Generic;

namespace dotnetNES.Engine.Utilities
{
    internal static class OpCodeLookup
    {
        internal static Dictionary<int, OpCode> OpCodes = new Dictionary<int, OpCode>
        {
            { 0x00, new OpCode { Length = 1, Instruction = 0x00, Format = "BRK" } },
            { 0x01, new OpCode { Length = 2, Instruction = 0x01, Format = "ORA (${0},X)" } },
            { 0x05, new OpCode { Length = 2, Instruction = 0x05, Format = "ORA {0}" } },
            { 0x06, new OpCode { Length = 2, Instruction = 0x06, Format = "ASL {0}" } },
            { 0x08, new OpCode { Length = 1, Instruction = 0x08, Format = "PHP" } },
            { 0x09, new OpCode { Length = 2, Instruction = 0x09, Format = "ORA #${0}" } },
            { 0x10, new OpCode { Length = 2, Instruction = 0x10, Format = "BPL" } },
            { 0x11, new OpCode { Length = 2, Instruction = 0x11, Format = "ORA (${0}),Y" } },
            { 0x15, new OpCode { Length = 2, Instruction = 0x15, Format = "ORA ${0},X" } },
            { 0x16, new OpCode { Length = 2, Instruction = 0x16, Format = "ASL ${0},X" } },
            { 0x18, new OpCode { Length = 1, Instruction = 0x18, Format = "CLC" } },
            { 0x19, new OpCode { Length = 3, Instruction = 0x19, Format = "ORA ${0}{1},Y" } },
            { 0x20, new OpCode { Length = 3, Instruction = 0x20, Format = "JSR {0}{1}" } },
            { 0x21, new OpCode { Length = 2, Instruction = 0x21, Format = "AND (${0},X)" } },
            { 0x24, new OpCode { Length = 2, Instruction = 0x24, Format = "BIT {0}" } },
            { 0x25, new OpCode { Length = 2, Instruction = 0x25, Format = "AND {0}" } },
            { 0x26, new OpCode { Length = 2, Instruction = 0x26, Format = "ROL {0}" } },
            { 0x28, new OpCode { Length = 1, Instruction = 0x28, Format = "PLP" } },
            { 0x29, new OpCode { Length = 2, Instruction = 0x29, Format = "AND #${0}" } },
            { 0x30, new OpCode { Length = 2, Instruction = 0x30, Format = "BMI" } },
            { 0x31, new OpCode { Length = 2, Instruction = 0x31, Format = "AND (${0}),Y" } },
            { 0x35, new OpCode { Length = 2, Instruction = 0x35, Format = "AND ${0},X" } },
            { 0x36, new OpCode { Length = 2, Instruction = 0x36, Format = "ROL ${0},X" } },
            { 0x38, new OpCode { Length = 1, Instruction = 0x38, Format = "SEC" } },
            { 0x39, new OpCode { Length = 3, Instruction = 0x39, Format = "AND ${0}{1},Y" } },
            { 0x40, new OpCode { Length = 1, Instruction = 0x40, Format = "RTI" } },
            { 0x41, new OpCode { Length = 2, Instruction = 0x41, Format = "EOR (${0},X)" } },
            { 0x45, new OpCode { Length = 2, Instruction = 0x45, Format = "EOR {0}" } },
            { 0x46, new OpCode { Length = 2, Instruction = 0x46, Format = "LSR {0}" } },
            { 0x48, new OpCode { Length = 1, Instruction = 0x48, Format = "PHA" } },
            { 0x49, new OpCode { Length = 2, Instruction = 0x49, Format = "EOR #${0}" } },
            { 0x50, new OpCode { Length = 2, Instruction = 0x50, Format = "BVC" } },
            { 0x51, new OpCode { Length = 2, Instruction = 0x51, Format = "EOR (${0}),Y" } },
            { 0x55, new OpCode { Length = 2, Instruction = 0x55, Format = "EOR ${0},X" } },
            { 0x56, new OpCode { Length = 2, Instruction = 0x56, Format = "LSR ${0},X" } },
            { 0x58, new OpCode { Length = 1, Instruction = 0x58, Format = "CLI" } },
            { 0x59, new OpCode { Length = 3, Instruction = 0x59, Format = "EOR ${0}{1},Y" } },
            { 0x60, new OpCode { Length = 1, Instruction = 0x60, Format = "RTS" } },
            { 0x61, new OpCode { Length = 2, Instruction = 0x61, Format = "ADC (${0},X)" } },
            { 0x65, new OpCode { Length = 2, Instruction = 0x65, Format = "ADC {0}" } },
            { 0x66, new OpCode { Length = 2, Instruction = 0x66, Format = "ROR {0}" } },
            { 0x68, new OpCode { Length = 1, Instruction = 0x68, Format = "PLA" } },
            { 0x69, new OpCode { Length = 2, Instruction = 0x69, Format = "ADC #${0}" } },
            { 0x70, new OpCode { Length = 2, Instruction = 0x70, Format = "BVS" } },
            { 0x71, new OpCode { Length = 2, Instruction = 0x71, Format = "ADC (${0}),Y" } },
            { 0x75, new OpCode { Length = 2, Instruction = 0x75, Format = "ADC ${0},X" } },
            { 0x76, new OpCode { Length = 2, Instruction = 0x76, Format = "ROR ${0},X" } },
            { 0x78, new OpCode { Length = 1, Instruction = 0x78, Format = "SEI" } },
            { 0x79, new OpCode { Length = 3, Instruction = 0x79, Format = "ADC ${0}{1},Y" } },
            { 0x81, new OpCode { Length = 2, Instruction = 0x81, Format = "STA (${0},X)" } },
            { 0x84, new OpCode { Length = 2, Instruction = 0x84, Format = "STY {0}" } },
            { 0x85, new OpCode { Length = 2, Instruction = 0x85, Format = "STA {0}" } },
            { 0x86, new OpCode { Length = 2, Instruction = 0x86, Format = "STX {0}" } },
            { 0x88, new OpCode { Length = 1, Instruction = 0x88, Format = "DEY" } },
            { 0x90, new OpCode { Length = 2, Instruction = 0x90, Format = "BCC" } },
            { 0x91, new OpCode { Length = 2, Instruction = 0x91, Format = "STA (${0}),Y" } },
            { 0x94, new OpCode { Length = 2, Instruction = 0x94, Format = "STY ${0},X" } },
            { 0x95, new OpCode { Length = 2, Instruction = 0x95, Format = "STA ${0},X" } },
            { 0x96, new OpCode { Length = 2, Instruction = 0x96, Format = "STX ${0},Y" } },
            { 0x98, new OpCode { Length = 1, Instruction = 0x98, Format = "TYA" } },
            { 0x99, new OpCode { Length = 3, Instruction = 0x99, Format = "STA ${0}{1},Y" } },
            { 0x8A, new OpCode { Length = 1, Instruction = 0x8A, Format = "TXA" } },
            { 0xA4, new OpCode { Length = 2, Instruction = 0xA4, Format = "LDY {0}" } },
            { 0xA5, new OpCode { Length = 2, Instruction = 0xA5, Format = "LDA {0}" } },
            { 0xA6, new OpCode { Length = 2, Instruction = 0xA6, Format = "LDX {0}" } },
            { 0xA8, new OpCode { Length = 1, Instruction = 0xA8, Format = "TAY" } },
            { 0xAA, new OpCode { Length = 1, Instruction = 0xAA, Format = "TAX" } },
            { 0xC4, new OpCode { Length = 2, Instruction = 0xC4, Format = "CPY {0}" } },
            { 0xC5, new OpCode { Length = 2, Instruction = 0xC5, Format = "CMP {0}" } },
            { 0xC6, new OpCode { Length = 2, Instruction = 0xC6, Format = "DEC {0}" } },
            { 0xE4, new OpCode { Length = 2, Instruction = 0xE4, Format = "CPX {0}" } },
            { 0xE5, new OpCode { Length = 2, Instruction = 0xE5, Format = "SBC {0}" } },
            { 0xE6, new OpCode { Length = 2, Instruction = 0xE6, Format = "INC {0}" } },
            { 0xF0, new OpCode { Length = 2, Instruction = 0xF0, Format = "BEQ" } },
            { 0x0A, new OpCode { Length = 1, Instruction = 0x0A, Format = "ASL A" } },
            { 0x0D, new OpCode { Length = 3, Instruction = 0x0D, Format = "ORA {0}{1}" } },
            { 0x0E, new OpCode { Length = 3, Instruction = 0x0E, Format = "ASL {0}{1}" } },
            { 0x1D, new OpCode { Length = 3, Instruction = 0x1D, Format = "ORA ${0}{1},X" } },
            { 0x1E, new OpCode { Length = 3, Instruction = 0x1E, Format = "ASL ${0}{1},X" } },
            { 0x2A, new OpCode { Length = 1, Instruction = 0x2A, Format = "ROL A" } },
            { 0x2C, new OpCode { Length = 3, Instruction = 0x2C, Format = "BIT {0}{1}" } },
            { 0x2D, new OpCode { Length = 3, Instruction = 0x2D, Format = "AND {0}{1}" } },
            { 0x2E, new OpCode { Length = 3, Instruction = 0x2E, Format = "ROL {0}{1}" } },
            { 0x3D, new OpCode { Length = 3, Instruction = 0x3D, Format = "AND ${0}{1},X" } },
            { 0x3E, new OpCode { Length = 3, Instruction = 0x3E, Format = "ROL ${0}{1},X" } },
            { 0x4A, new OpCode { Length = 1, Instruction = 0x4A, Format = "LSR A" } },
            { 0x4C, new OpCode { Length = 3, Instruction = 0x4C, Format = "JMP ${0}{1}" } },
            { 0x4D, new OpCode { Length = 3, Instruction = 0x4D, Format = "EOR {0}" } },
            { 0x4E, new OpCode { Length = 3, Instruction = 0x4E, Format = "LSR {0}" } },
            { 0x5D, new OpCode { Length = 3, Instruction = 0x5D, Format = "EOR ${0},X" } },
            { 0x5E, new OpCode { Length = 3, Instruction = 0x5E, Format = "LSR ${0},X" } },
            { 0x6A, new OpCode { Length = 1, Instruction = 0x6A, Format = "ROR A" } },
            { 0x6C, new OpCode { Length = 3, Instruction = 0x6C, Format = "JMP $({0}{1})" } },
            { 0x6D, new OpCode { Length = 3, Instruction = 0x6D, Format = "ADC {0}" } },
            { 0x6E, new OpCode { Length = 3, Instruction = 0x6E, Format = "ROR {0}" } },
            { 0x7D, new OpCode { Length = 3, Instruction = 0x7D, Format = "ADC ${0},X" } },
            { 0x7E, new OpCode { Length = 3, Instruction = 0x7E, Format = "ROR ${0},X" } },
            { 0x8C, new OpCode { Length = 3, Instruction = 0x8C, Format = "STY {0}{1}" } },
            { 0x8D, new OpCode { Length = 3, Instruction = 0x8D, Format = "STA {0}{1}" } },
            { 0x8E, new OpCode { Length = 3, Instruction = 0x8E, Format = "STX {0}{1}" } },
            { 0x9A, new OpCode { Length = 1, Instruction = 0x9A, Format = "TXS" } },
            { 0x9D, new OpCode { Length = 3, Instruction = 0x9D, Format = "STA ${0},X" } },
            { 0xA0, new OpCode { Length = 2, Instruction = 0xA0, Format = "LDY #${0}" } },
            { 0xA1, new OpCode { Length = 2, Instruction = 0xA1, Format = "LDA (${0},X)" } },
            { 0xA2, new OpCode { Length = 2, Instruction = 0xA2, Format = "LDX #${0}" } },
            { 0xA9, new OpCode { Length = 2, Instruction = 0xA9, Format = "LDA #${0}" } },
            { 0xAC, new OpCode { Length = 3, Instruction = 0xAC, Format = "LDY {0}{1}" } },
            { 0xAD, new OpCode { Length = 3, Instruction = 0xAD, Format = "LDA {0}{1}" } },
            { 0xAE, new OpCode { Length = 3, Instruction = 0xAE, Format = "LDX {0}{1}" } },
            { 0xB0, new OpCode { Length = 2, Instruction = 0xB0, Format = "BCS" } },
            { 0xB1, new OpCode { Length = 2, Instruction = 0xB1, Format = "LDA (${0}),Y" } },
            { 0xB4, new OpCode { Length = 2, Instruction = 0xB4, Format = "LDY ${0},X" } },
            { 0xB5, new OpCode { Length = 2, Instruction = 0xB5, Format = "LDA ${0},X" } },
            { 0xB6, new OpCode { Length = 2, Instruction = 0xB6, Format = "LDX ${0},Y" } },
            { 0xB8, new OpCode { Length = 1, Instruction = 0xB8, Format = "CLV" } },
            { 0xB9, new OpCode { Length = 3, Instruction = 0xB9, Format = "LDA ${0}{1},Y" } },
            { 0xBA, new OpCode { Length = 1, Instruction = 0xBA, Format = "TSX" } },
            { 0xBC, new OpCode { Length = 3, Instruction = 0xBC, Format = "LDY ${0}{1},X" } },
            { 0xBD, new OpCode { Length = 3, Instruction = 0xBD, Format = "LDA ${0}{1},X" } },
            { 0xBE, new OpCode { Length = 3, Instruction = 0xBE, Format = "LDX ${0}{1},Y" } },
            { 0xC0, new OpCode { Length = 2, Instruction = 0xC0, Format = "CPY #${0}" } },
            { 0xC1, new OpCode { Length = 2, Instruction = 0xC1, Format = "CMP (${0},X)" } },
            { 0xC8, new OpCode { Length = 1, Instruction = 0xC8, Format = "INY" } },
            { 0xC9, new OpCode { Length = 2, Instruction = 0xC9, Format = "CMP #${0}" } },
            { 0xCA, new OpCode { Length = 1, Instruction = 0xCA, Format = "DEX" } },
            { 0xCC, new OpCode { Length = 3, Instruction = 0xCC, Format = "CPY {0}{1}" } },
            { 0xCD, new OpCode { Length = 3, Instruction = 0xCD, Format = "CMP {0}{1}" } },
            { 0xCE, new OpCode { Length = 3, Instruction = 0xCE, Format = "DEC {0}{1}" } },
            { 0xD0, new OpCode { Length = 2, Instruction = 0xD0, Format = "BNE" } },
            { 0xD1, new OpCode { Length = 2, Instruction = 0xD1, Format = "CMP (${0}),Y" } },
            { 0xD5, new OpCode { Length = 2, Instruction = 0xD5, Format = "CMP ${0},X" } },
            { 0xD6, new OpCode { Length = 2, Instruction = 0xD6, Format = "DEC ${0},X" } },
            { 0xD8, new OpCode { Length = 1, Instruction = 0xD8, Format = "CLD" } },
            { 0xD9, new OpCode { Length = 3, Instruction = 0xD9, Format = "CMP ${0}{1},Y" } },
            { 0xDD, new OpCode { Length = 3, Instruction = 0xDD, Format = "CMP ${0}{1},X" } },
            { 0xDE, new OpCode { Length = 3, Instruction = 0xDE, Format = "DEC ${0}{1},X" } },
            { 0xE0, new OpCode { Length = 2, Instruction = 0xE0, Format = "CPX #${0}" } },
            { 0xE1, new OpCode { Length = 2, Instruction = 0xE1, Format = "SBC (${0},X)" } },
            { 0xE8, new OpCode { Length = 1, Instruction = 0xE8, Format = "INX" } },
            { 0xE9, new OpCode { Length = 2, Instruction = 0xE9, Format = "SBC #${0}" } },
            { 0xEA, new OpCode { Length = 1, Instruction = 0xEA, Format = "NOP" } },
            { 0xEC, new OpCode { Length = 3, Instruction = 0xEC, Format = "CPX {0}{1}" } },
            { 0xED, new OpCode { Length = 3, Instruction = 0xED, Format = "SBC {0}{1}" } },
            { 0xEE, new OpCode { Length = 3, Instruction = 0xEE, Format = "INC {0}{1}" } },
            { 0xF1, new OpCode { Length = 2, Instruction = 0xF1, Format = "SBC (${0}),Y" } },
            { 0xF5, new OpCode { Length = 2, Instruction = 0xF5, Format = "SBC ${0},X" } },
            { 0xF6, new OpCode { Length = 2, Instruction = 0xF6, Format = "INC ${0},X" } },
            { 0xF8, new OpCode { Length = 1, Instruction = 0xF8, Format = "SED" } },
            { 0xF9, new OpCode { Length = 3, Instruction = 0xF9, Format = "SBC ${0}{1},Y" } },
            { 0xFD, new OpCode { Length = 3, Instruction = 0xFD, Format = "SBC ${0}{1},X" } },
            { 0xFE, new OpCode { Length = 3, Instruction = 0xFE, Format = "INC ${0}{1},X" } }
        };
    }
}
